language: ruby
rvm:
  - 1.9
  - 2.1
cache: bundler
sudo: false
bundler_args: --without development
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.1.0" STRICT_VARIABLES=yes
matrix:
  allow_failures:
    - env: PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
notifications:
  email:
    - roman.plessl@nine.ch
